include: package:effective_dart/analysis_options.yaml


analyzer:
  exclude:
    - build/**
  strong-mode:
    implicit-casts: true
  errors:
    todo: warning

#exclude_rules:
#  - public_member_api_docs

linter:
  rules:
    - camel_case_types
    - prefer_const_constructors
    - cancel_subscriptions
    - empty_statements
    - literal_only_boolean_expressions
    - no_logic_in_create_state
    - test_types_in_equals
    - unnecessary_statements
    - throw_in_finally
    - use_key_in_widget_constructors
    - always_require_non_null_named_parameters
    - annotate_overrides
    - avoid_bool_literals_in_conditional_expressions
    - avoid_double_and_int_checks
    - avoid_init_to_null
    - avoid_returning_null
    - avoid_setters_without_getters
    - avoid_single_cascade_in_expression_statements
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - await_only_futures
    - cascade_invocations
    - prefer_asserts_with_message
    - prefer_asserts_in_initializer_lists
    - prefer_const_literals_to_create_immutables
    - prefer_constructors_over_static_methods
    - library_prefixes
    - curly_braces_in_flow_control_structures
    - directives_ordering
    - file_names
    - library_names
    - implementation_imports
    - use_to_and_as_if_applicable
    - unnecessary_getters_setters
    - unnecessary_await_in_return
    - unawaited_futures
    - use_string_buffers
    - unnecessary_lambdas
    - unnecessary_brace_in_string_interps
    - sort_unnamed_constructors_first
    - sort_constructors_first
    - prefer_inlined_adds