name: responsive_page
description: Responsive Stateful or Stateless Widget. Define 4 different build methods and save your state..
version: 0.0.4
authors:
  - mehmedyaz@gmail.com
repository: https://github.com/Mehmetyaz/responsive_widget.git
homepage: https://github.com/Mehmetyaz/responsive_widget.git


environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:

  flutter:
    sdk: flutter

dev_dependencies:
  effective_dart: ^1.3.1
  flutter_test:
    sdk: flutter

flutter:

